version: "3.9"
services:
    express:
        build: .
        ports:
            - "5000:5000"
        expose:
            - 5000
        depends_on:
            - mysqldb
        environment:
            CHOKIDAR_USEPOLLING: "true"
            DB_HOST: mysqldb
            DB_PORT: 3306
            SERVER_PORT: 5000
            DB_NAME: AssociationCoranique
            DB_USERNAME: root
            DB_PASSWORD: ""

    mysqldb:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3307:3306"
        expose:
            - 3307
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: AssociationCoranique
            MYSQL_ROOT_HOST: localhost
            MYSQL_USER: root
        volumes:
            - db:/var/lib/mysql
        networks:
            - default
volumes:
    db:

networks:
    default:
