version: "3.9"
services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
        volumes:
            - db:/var/lib/mysql

    express:
        depends_on:
            - mysqldb
        build: .
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $NODE_SERVER_LOCAL_PORT:$NODE_SERVER_DOCKER_PORT
        environment:
            - DB_HOST=$MYSQL_HOST
            - DB_USER=$MYSQL_USER
            - DB_PASSWORD=$MYSQL_ROOT_PASSWOR
            - DB_NAME=$MYSQL_DATABASE
            - DB_PORT=$MYSQL_DOCKER_PORT
        stdin_open: true
        tty: true
volumes:
    db:
